### ISSUE TITLE
Alternative usage?

### ISSUE THREAD

**Issue by emms007** [sawhney17/logseq-go-now#2]
Thanks for the plugin.
Would there be away to have this logic available without quitting the page where I am at currently?

One example: _I am in a "essay page" and I just have a great thought. I want to have this added to my journal. Is there a way I can publish to my journal without navigating away from my "essay page"?_

I wonder if a plugin could allow to perform one of the following actions alternatively:
- show me a prompt where I can just added my thought. It will be added to my daily journal.
- pop the journal in the right-side-bar and allow me to editing. This is similar to your current plugin, but will display the journal on the sidebar.

**Comment by sawhney17** [comment]
The quick-todo plugin may be what you’re after.

**Comment by emms007** [comment]
Totally, thanks
