### ISSUE TITLE
The command should not select the new block in the journal

### ISSUE THREAD

**Issue by galligan** [sawhney17/logseq-go-now#3]
## Current behavior
When I use `Mod+G`, the plugin takes me to today's journal, with a new block at the bottom, adds the cursor, but then selects the block. I'm unable to immediately start typing.

## Expected behavior
When I use `Mod+G` I should return to today's journal, at the bottom, with the cursor activated and ready to type.

**Comment by sawhney17** [comment]
You should be able to hit enter when the block is selected, but I guess I could make the plugin automatically register a shortcut

**Comment by galligan** [comment]
Or perhaps it's configurable what the action does? Could either select, or drop the cursor in that new block?

**Comment by oluckyman** [comment]
I guess there are use cases when you `mod+g` and _not_ pressing `enter`, but my reason to install this plugin was to start typing in today's journal, so I always hit `enter` after `mod+g`.
+1 for making the plugin to do it automatically.

Thanks for your efforts!

**Comment by sawhney17** [comment]
Should work now in the latest version. Just configure it in plugin settings.

**Comment by galligan** [comment]
FYI, I tried configuring for "Enter" and it didn't respect the choice. Using `mod+g` still only focuses on the block.

Here are my settings:
<img width="975" alt="CleanShot 2022-07-03 at 14 32 23@2x" src="https://user-images.githubusercontent.com/25037981/177052761-a62a09f2-2088-48e6-85ca-db21f9a0fde3.png">

**Comment by sawhney17** [comment]
Can you check console?

**Comment by galligan** [comment]
<img width="553" alt="CleanShot 2022-07-05 at 12 02 14@2x" src="https://user-images.githubusercontent.com/25037981/177369781-2d4ad328-b1e0-4dc6-adf8-76cf73a4773a.png">

**Comment by sawhney17** [comment]
Ooh, yeah. Will just push a fix.
